name: Tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

permissions:
  contents: read

env:
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: db_trilha
  DB_USERNAME: root
  DB_PASSWORD: root

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_trilha
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --default-authentication-plugin=mysql_native_password

    name: PHP 8.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql
          coverage: none

      - name: Copy environment file
        run: cp .env.example .env
        
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Generate app key
        run: php artisan key:generate

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y default-mysql-client

      - name: Debug DB connection
        run: |
          php -r '
          $link = mysqli_connect(getenv("DB_HOST"), getenv("DB_USERNAME"), getenv("DB_PASSWORD"));
          if (!$link) {
              echo "MySQL connection failed: " . mysqli_connect_error();
              exit(1);
          }
          echo "MySQL is up and running.\n";
          mysqli_close($link);
          '

      - name: Sleep a bit for MySQL
        run: sleep 5

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Execute tests
        run: vendor/bin/phpunit
